// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$0 from './islands/Button.tsx';
import * as $$1 from './islands/Card.tsx';
import * as $$2 from './islands/CardSection.tsx';
import * as $$3 from './islands/ContactSection.tsx';
import * as $$4 from './islands/Error.tsx';
import * as $$5 from './islands/Hero.tsx';
import * as $$6 from './islands/Nav.tsx';
import * as $$7 from './islands/TechnologiesSection.tsx';
import * as $2 from './routes/api/email.ts';
import * as $3 from './routes/api/joke/daily.ts';
import * as $4 from './routes/api/joke/index.ts';
import * as $5 from './routes/api/ping.ts';
import * as $6 from './routes/index.tsx';
import * as $7 from './routes/snake-game.tsx';
import * as $8 from './routes/snake.tsx';
import * as $0 from './routes/_404.tsx';
import * as $1 from './routes/_500.tsx';

const manifest = {
  routes: {
    './routes/_404.tsx': $0,
    './routes/_500.tsx': $1,
    './routes/api/email.ts': $2,
    './routes/api/joke/daily.ts': $3,
    './routes/api/joke/index.ts': $4,
    './routes/api/ping.ts': $5,
    './routes/index.tsx': $6,
    './routes/snake-game.tsx': $7,
    './routes/snake.tsx': $8,
  },
  islands: {
    './islands/Button.tsx': $$0,
    './islands/Card.tsx': $$1,
    './islands/CardSection.tsx': $$2,
    './islands/ContactSection.tsx': $$3,
    './islands/Error.tsx': $$4,
    './islands/Hero.tsx': $$5,
    './islands/Nav.tsx': $$6,
    './islands/TechnologiesSection.tsx': $$7,
  },
  baseUrl: import.meta.url,
};

export default manifest;
