// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_500.tsx";
import * as $2 from "./routes/api/email.ts";
import * as $3 from "./routes/api/joke/daily.ts";
import * as $4 from "./routes/api/joke/index.ts";
import * as $5 from "./routes/api/ping.ts";
import * as $6 from "./routes/index.tsx";
import * as $7 from "./routes/technologies.tsx";
import * as $$0 from "./islands/Nav.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_500.tsx": $1,
    "./routes/api/email.ts": $2,
    "./routes/api/joke/daily.ts": $3,
    "./routes/api/joke/index.ts": $4,
    "./routes/api/ping.ts": $5,
    "./routes/index.tsx": $6,
    "./routes/technologies.tsx": $7,
  },
  islands: {
    "./islands/Nav.tsx": $$0,
  },
  baseUrl: import.meta.url,
};

export default manifest;
