export const technologies = [
  { link: 'https://nextjs.org', title: 'Next JS', description: 'A fullstack framework for React with SSR and SSG that provides built-in optimizations.' },
  { link: 'https://reactjs.org', title: 'React', description: "The world's most popular non-opinionated frontend UI framework. Focuses on functional UI." },
  { link: 'https://nodejs.org', title: 'NodeJS', description: "The first ever server-side JavaScript runtime built on Google Chrome's V8 JavaScript engine." },
  { link: 'https://www.typescriptlang.org/', title: 'TypeScript', description: 'A better version of JavaScript that privides static typing to the language,' },
  { link: 'https://deno.land', title: 'Deno', description: 'The successor to NodeJS built with Rust and focused on TypeScript, efficiency, and simplicity.' },
  {
    link: 'https://sass-lang.com',
    title: 'SCSS',
    description: 'A better version of CSS that provides support for nested selectors, functions, mixins and so much more.',
  },
  {
    link: 'https://expressjs.com',
    title: 'Express',
    description: 'The most popular NodeJS library for http servers that allows for JavaScript based APIs and web apps.',
  },
  {
    link: 'https://www.docker.com',
    title: 'Docker',
    description: 'Containerization for apps that gives standardization and recreation abilities to reduce "it works on my machine" problems.',
  },
  { link: 'https://fresh.deno.dev', title: 'Fresh', description: 'A brand-new React framework built and used with Deno (used to create this site)' },
  { link: 'https://www.figma.com/', title: 'Figma', description: 'Frontend UI design tool for team-based web design and optimized collaboration.' },
  {
    link: 'https://www.vercel.com/',
    title: 'Vercel',
    description: 'Serverless hosting for web apps like NextJS, React, Angular, Vite, etc. (creators of Next JS).',
  },
  { link: 'https://www.mongodb.com/', title: 'MongoDB', description: 'Extremely popular NoSQL database.' },
  { link: 'https://www.heroku.com/', title: 'Heroku', description: 'Cloud hosting for applications.' },
  { link: 'https://www.netlify.com/', title: 'Netlify', description: 'Hosting service for static web apps.' },
  {
    link: 'https://www.javascript.com/',
    title: 'JavaScript',
    description: 'The most popular coding language of today; powers the web, keeps sites functioning.',
  },
  { link: 'https://developer.mozilla.org/en-US/docs/Web/CSS', title: 'CSS', description: 'The universal frontend styling language.' },
  { link: 'https://webpack.js.org/', title: 'Webpack', description: 'JavaScript module bundler/builder.' },
  {
    link: 'https://developer.salesforce.com/docs/component-library/documentation/en/lwc',
    title: 'LWC',
    description: "Salesforce's frontend framework (Lightning Web Components).",
  },
  { link: 'https://angular.io/', title: 'Angular', description: 'A popular, opinionated frontend UI framework created by Google.' },
  { link: 'https://vitejs.dev/', title: 'Vite', description: 'The better, faster, newer version of Webpack (uses HMR).' },
  { link: 'https://lit.dev/', title: 'Lit', description: 'Abstraction framework for WebComponents.' },
  { link: 'https://ionic.io/', title: 'Ionic', description: 'Fullstack framework for building applications.' },
  { link: 'https://prisma.io/', title: 'Prisma', description: 'A TypeScript-based ORM (abstraction layer) for SQL database management.' },
  { link: 'https://electronjs.org/', title: 'Electron', description: 'Creates desktop apps with HTML, CSS and JavaScript.' },
];
